spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      mvc:
        routes:
          - id: external-movie-service
            uri: lb://external-movie-service
            predicates:
              - Path=/api/movies/**
            filters:
              - "StripPrefix=1"
          - id: swagger
            uri: lb://external-movie-service
            predicates:
              - Path=/swagger-ui.html, /v3/api-docs/**
            filters:
              - "StripPrefix=0"

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/