spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      mvc:
        routes:
          - id: external-movie-service
            uri: lb://external-movie-service
            predicates:
              - Path=/api/movies/**
            filters:
              - "StripPrefix=1"
          - id: swagger
            uri: lb://external-movie-service
            predicates:
              - Path=/swagger-ui/index.html, /v3/api-docs/**
            filters:
              - "StripPrefix=0"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://srv29.mikr.us:40053/realms/Shair13
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 20180

eureka:
  client:
    service-url:
      defaultZone: http://localhost:30180/eureka/

springdoc:
  swagger-ui:
    oauth:
      client-id: movie-rest-api
      client-secret: mPEQY5rJaAmylsSuU6btHeqv5xrAUp3P