spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      mvc:
        routes:
          - id: external-movie-service
            uri: lb://external-movie-service
            predicates:
              - Path=/api/movies/**
            filters:
              - "StripPrefix=1"

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/